### ISSUE TITLE
add feature categories and list features in documentation

### ISSUE THREAD

**Issue by marabuuu** [haesleinhuepf/napari-simpleitk-image-processing#20]
It would be good to list in the documentation the available features in their categories similar to the feature catalogue in [`napari-skimage-regionprops`](https://github.com/haesleinhuepf/napari-skimage-regionprops#Features).
I am happy to do that 😸

**Comment by haesleinhuepf** [comment]
Done in https://github.com/haesleinhuepf/napari-simpleitk-image-processing/pull/21
